name: Push to Amazon ECR
description: Create the repository, if it doesn't exist, and push a docker image to Amazon ECR.
inputs:
  ecr_repository:
    description: The complete repository name from ECR {BU}/{TEAM}/{PROJECT} (ex. cross/devtools/devtools-scripts).
    required: true
  tags:
    description: Comma-separated string of ECR image tags (ex. latest, 1.0.0).
    required: true
  x9_container_distro:
    description: Distro of the target Docker image, for security scan. Select a Dockerfile prefix from X9Containers local folder with a preferred distro and tools (ex. debian.clamav.trivy).
    required: false
    default: distroless.trivy
  x9_container_branch:
    description: Branch of the x9 containers to use. Mostly for testing purposes.
    required: false
    default: julianoborba-patch-1
  minimal_severity:
    description: Minimal threat detection level, for security scan (ex. CRITICAL / HIGH / MEDIUM / LOW / UNKNOWN).
    required: false
    default: CRITICAL
  ignore_threats:
    description: If true, don't interrupt workflow if has security findings, during security scan.
    required: false
    default: 'false'
  trivy_ignore_url:
    description: URL of the .trivyignore the action will use during the build (Only valid for Trivy containers).
    required: false
    default: https://raw.githubusercontent.com/olxbr/aws-ecr-push-action/main/X9Containers/.trivyignore
outputs:
  repository_uri:
    description: The URI of the ECR registry i.e. aws_account_id.dkr.ecr.region.amazonaws.com.
runs:
  using: 'node12'
  pre: 'dist/index.js'
  main: 'dist/index.js'
  post: 'dist/index.js'
