name: Push to Amazon ECR
description: Create the repository, if it doesn't exist, and push a docker image to Amazon ECR.
inputs:
  ecr_repository:
    description: The complete repository name from ECR {BU}/{TEAM}/{PROJECT} (ex. cross/devtools/devtools-scripts).
    required: true
    default: cross/devtools/devtools-scripts
  tags:
    description: Comma-separated string of ECR image tags (ex. latest, 1.0.0).
    required: true
    default: latest
  x9_container_distro:
    description: Distro of the target Docker image, for security scan. Select a Dockerfile prefix from X9Containers local folder with a preferred distro and tools (ex. debian.clamav.trivy).
    required: false
    default: distroless.trivy
  x9_container_branch:
    description: Branch of the x9 containers to use. Mostly for testing purposes.
    required: false
    default: main
  minimal_severity:
    description: Minimal threat detection level, for security scan (ex. CRITICAL / HIGH / MEDIUM / LOW / UNKNOWN).
    required: false
    default: CRITICAL
  ignore_threats:
    description: If true, don't interrupt workflow if has security findings, during security scan.
    required: false
    default: "false"
  trivy_ignore_file:
    description: FILE of the .trivyignore the action will use during the build (Only valid for Trivy containers).
    required: false
    default: .trivyignore
  keep_images:
    description: The quantity of images to keep (ex. -1 will keep all images, 0 will delete them all, 10 the last 10 new images will be kept)
    required: false
    default: 100
  build_kit:
    description: The build kit to use (ex. buildkitd). Enable buildkitd can speed up the build process.
    default: 0
outputs:
  repository_uri:
    description: The URI of the ECR registry i.e. aws_account_id.dkr.ecr.region.amazonaws.com.
runs:
  using: "node16"
  pre: "dist/pre/index.js"
  main: "dist/main/index.js"
  post: "dist/post/index.js"
