name: Blackbox

on:
  repository_dispatch:
    types: [event-trigger]
  workflow_dispatch: ~

# .github/workflows/blackbox-workflow.yml
jobs:
    run-blackbox-action:
        runs-on: [self-hosted, tech-radar]
        steps:
            - uses: actions/checkout@v3

            - id: blackbox
              uses: olxbr/blackbox-action@v1
              with:
                config: ${{ secrets.BLACK_BOX_CONFIG }}
              env:
                DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
