name: Build and push dist

on:
  pull_request:
    branches: [ main ]

jobs:
  build-and-push-dist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn
        
      - name: Build dist
        run: yarn build

      - name: Commit dist
        uses: EndBug/add-and-commit@v7
        with:
          add: 'dist/index.js'
          default_author: github_actions
          message: 'Build dist'
