name: Build and push dist

on:
  pull_request:
    branches: [ main ]
  push:
    branches:
    - main

jobs:
  build-and-push-dist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: |
            ./node_modules
            */**/node_modules
          key: ${{ runner.os }}-aws-ecr-push-action-node-modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-aws-ecr-push-action-node-modules

      - name: Install dependencies
        run: yarn install --frozen-lockfile
        
      - name: Build dist
        run: yarn build
        env:
          NODE_OPTIONS: --openssl-legacy-provider

      - name: Commit dist
        uses: EndBug/add-and-commit@v9
        with:
          add: 'dist/main/index.js'
          default_author: github_actions
          message: 'Build dist'
