name: "Push latest ClamAV and Trivy Docker Images to ECR"
on:
  schedule:
    - cron: "0 10 * * SUN"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      # CLAMAV
      - name: Pull ClamAV
        run: |
          docker pull clamav/clamav:latest

      - name: Apply new tag
        run: |
          docker tag clamav/clamav:latest ${{ secrets.CONTAINER_REGISTRY_HOST }}/cross/devsecops/clamav:latest

      - name: Push image to AWS ECR
        env:
          AWS_ACCOUNT_ID: ${{ secrets.AWS_CROSS_ACCOUNT_ID }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_CROSS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_CROSS_SECRET_ACCESS_KEY }}
          AWS_PRINCIPAL_RULES: ${{ secrets.AWS_PRINCIPAL_RULES }}
        uses: olxbr/aws-ecr-push-action@v1
        with:
          ecr_repository: cross/devsecops/clamav
          tags: latest

      # TRIVY
      - name: Pull Trivy
        run: |
          docker pull aquasec/trivy:latest

      - name: Apply new tag
        run: |
          docker tag aquasec/trivy:latest ${{ secrets.CONTAINER_REGISTRY_HOST }}/cross/devsecops/trivy:latest

      - name: Push image to AWS ECR
        env:
          AWS_ACCOUNT_ID: ${{ secrets.AWS_CROSS_ACCOUNT_ID }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_CROSS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_CROSS_SECRET_ACCESS_KEY }}
          AWS_PRINCIPAL_RULES: ${{ secrets.AWS_PRINCIPAL_RULES }}
        uses: olxbr/aws-ecr-push-action@v1
        with:
          ecr_repository: cross/devsecops/trivy
          tags: latest
