name: Release new action version
on:
  release:
    types: [released]
  workflow_dispatch:
    inputs:
      TAG_NAME:
        description: 'Tag name that the major tag will point to'
        required: true

env:
  TAG_NAME: ${{ github.event.inputs.TAG_NAME || github.event.release.tag_name }}
permissions:
  contents: write

jobs:
  trigger:
    name: Runs integration tests
    runs-on: ubuntu-latest
    steps:
      - name: Trigger
        run: |
          curl -X POST https://api.github.com/repos/olxbr/action-tester/dispatches \
            -H 'Accept: application/vnd.github.everest-preview+json' \
            -H 'Authorization: token ${{ secrets.PAT }}' \
            --data '{"event_type": "ecr-push-major", "client_payload": { "version": "${GITHUB_REF#refs/heads/}"}}'
            
      - name: Wait 2min
        run: |
          sleep 120s
          
  update_tag:
    name: Update the major tag to include the ${{ github.event.inputs.TAG_NAME || github.event.release.tag_name }} changes
    runs-on: ubuntu-latest
    needs: [trigger]
    steps:
    - name: Update the ${{ env.TAG_NAME }} tag
      id: update-major-tag
      uses: actions/publish-action@v0.1.0
      with:
        source-tag: ${{ env.TAG_NAME }}
