name: Unittest

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: |
            ./node_modules
            */**/node_modules
          key: ${{ runner.os }}-aws-ecr-push-action-node-modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-aws-ecr-push-action-node-modules

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build dist
        run: yarn build
        env:
          NODE_OPTIONS: --openssl-legacy-provider

      - name: Run tests
        env:
          AWS_ACCESS_KEY_ID: "AKIAIOSFODNN7EXAMPLE"
          AWS_SECRET_ACCESS_KEY: "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
        run: yarn test
